version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "gradle"
    directory: "/mobile/android"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "monthly"
      day: "tuesday"