version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/mobile/android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "daily"